// Per-bid pricing: a flat $0.05 per square foot of the plan's total area (summed across
// data.areas, as generated by the takeoff AI), with a $15 minimum so tiny/partial plans
// still cover the fixed cost of running a takeoff. $15 mirrors the old "simple" tier's
// floor — the cheapest bid the system has historically charged, kept as a sane baseline
// rather than picked arbitrarily.

/** Cents charged per square foot. */
export const SQFT_RATE_CENTS = 5; // $0.05/sq ft

/** Minimum charge per bid, in cents, regardless of square footage. */
export const MIN_PRICE_CENTS = 1500; // $15

/** Flat monthly price, in cents, for the unlimited-bids subscription plan. */
export const MONTHLY_PLAN_PRICE_CENTS = 14900; // $149/mo

/** Shown to the GC when a takeoff has no usable square footage to price from. */
export const INVALID_SQUARE_FEET_MESSAGE =
  "This takeoff doesn't have usable square footage yet. Open the Takeoff tab, check the " +
  'areas list, and make sure at least one area has a square footage greater than 0, then try again.';

/**
 * Sums `squareFeet` across a takeoff's areas, defensively. Missing/non-numeric/negative
 * values on an individual area are clamped to 0. Returns the raw (unrounded) total; 0 or
 * negative means "no usable square footage" — that is never a valid billable total.
 */
export function totalSquareFeetRaw(areas: { squareFeet?: number | null }[] | null | undefined): number {
  return (areas ?? []).reduce((sum, a) => sum + Math.max(0, Number(a?.squareFeet) || 0), 0);
}

/**
 * Price in cents for a takeoff's total square footage, or `null` if the total is 0 or
 * negative (i.e. unusable) — callers must treat `null` as a hard block on charging, never
 * fall back to a default price. Checked before rounding, so a small-but-positive raw total
 * (e.g. 0.4 sq ft) isn't misclassified as invalid just because it would round to 0.
 */
export function priceCentsForSquareFeet(rawTotalSquareFeet: number): number | null {
  if (rawTotalSquareFeet <= 0) return null;
  return Math.max(MIN_PRICE_CENTS, Math.round(rawTotalSquareFeet * SQFT_RATE_CENTS));
}

/**
 * Rounds a raw total for display/storage as a whole number of square feet. Floors at 1 for
 * any genuinely-positive raw total so a successfully-priced bid never displays "0 sq ft".
 */
export function displaySquareFeet(rawTotalSquareFeet: number): number {
  if (rawTotalSquareFeet <= 0) return 0;
  return Math.max(1, Math.round(rawTotalSquareFeet));
}
