// Bid proposal PDF generation, ported from the share-bid-pdf edge function.
// pdf-lib runs unchanged on Node.
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface TakeoffItem { description: string; quantity: number; unit: string; }
interface TakeoffSection { trade: string; items: TakeoffItem[]; }
interface DelegationData { subId: string; prices: Record<string, number>; approvedAt?: string; }
interface BidData {
  prices: Record<string, number>;
  delegations?: Record<string, DelegationData>;
  overheadPct: number;
  profitPct: number;
  contingencyPct: number;
  finalizedAt?: string;
}
export interface BidTakeoffData { projectName: string; sections: TakeoffSection[]; bid?: BidData; }

function fmtMoney(n: number): string {
  return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export async function generateBidPdf(
  data: BidTakeoffData,
  sharingMode: 'full' | 'summary',
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const W = 612, H = 792, MARGIN = 50;
  let page = pdfDoc.addPage([W, H]);
  let y = H - MARGIN;

  const gray = rgb(0.55, 0.55, 0.55);
  const dark = rgb(0.1, 0.1, 0.1);
  const light = rgb(0.78, 0.78, 0.78);
  const navy = rgb(0.12, 0.20, 0.46);
  const blue = rgb(0.145, 0.388, 0.922); // #2563eb

  const text = (str: string, x: number, yy: number, size: number, bold = false, color = dark) => {
    page.drawText(str, { x, y: yy, size, font: bold ? boldFont : font, color });
  };

  const rule = (yy: number, x1 = MARGIN, x2 = W - MARGIN, thickness = 0.5, color = light) => {
    page.drawLine({ start: { x: x1, y: yy }, end: { x: x2, y: yy }, thickness, color });
  };

  const checkY = (needed: number) => {
    if (y - needed < MARGIN + 30) {
      text('Generated by BidWise', MARGIN, MARGIN, 7, false, light);
      page = pdfDoc.addPage([W, H]);
      y = H - MARGIN;
    }
  };

  // ── Logo (centered) ──
  const logoSize = 32;
  const bidW = boldFont.widthOfTextAtSize('Bid', 20);
  const logoTextW = boldFont.widthOfTextAtSize('BidWise', 20);
  const logoBlockW = logoSize + 10 + logoTextW;
  const logoX = (W - logoBlockW) / 2;
  const iconBottom = y - logoSize;
  page.drawRectangle({ x: logoX, y: iconBottom, width: logoSize, height: logoSize, color: blue });
  page.drawLine({ start: { x: logoX + 8.67, y: iconBottom + 15 }, end: { x: logoX + 13.67, y: iconBottom + 10 }, thickness: 3, color: rgb(1, 1, 1) });
  page.drawLine({ start: { x: logoX + 13.67, y: iconBottom + 10 }, end: { x: logoX + 23.33, y: iconBottom + 20.67 }, thickness: 3, color: rgb(1, 1, 1) });
  const wordX = logoX + logoSize + 10;
  const wordY = iconBottom + (logoSize - 20) / 2;
  text('Bid', wordX, wordY, 20, true, dark);
  text('Wise', wordX + bidW, wordY, 20, true, blue);
  y -= logoSize + 20;

  // ── Header ──
  text('Bid Proposal', MARGIN, y, 22, true, navy);
  y -= 28;
  text(data.projectName, MARGIN, y, 14, true);
  y -= 18;
  const finalDate = data.bid?.finalizedAt
    ? new Date(data.bid.finalizedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';
  text(`Finalized: ${finalDate}`, MARGIN, y, 9, false, gray);
  y -= 24;
  rule(y, MARGIN, W - MARGIN, 1, navy);
  y -= 20;

  // ── Column headers ──
  const COL = { desc: MARGIN, qty: MARGIN + 250, unit: MARGIN + 310, price: MARGIN + 370, total: W - MARGIN - 55 };
  if (sharingMode === 'full') {
    text('DESCRIPTION', COL.desc, y, 7, true, gray);
    text('QTY', COL.qty, y, 7, true, gray);
    text('UNIT', COL.unit, y, 7, true, gray);
    text('UNIT PRICE', COL.price, y, 7, true, gray);
    text('TOTAL', COL.total, y, 7, true, gray);
  } else {
    text('TRADE', COL.desc, y, 7, true, gray);
    text('SUBTOTAL', COL.total, y, 7, true, gray);
  }
  y -= 12;
  rule(y);
  y -= 10;

  const bid = data.bid!;
  const delegations = bid.delegations ?? {};
  let directCost = 0;

  const rowLabel = (label: string, value: string, bold = false) => {
    text(label, W - MARGIN - 195, y, 9, bold);
    const valX = W - MARGIN - font.widthOfTextAtSize(value, 9);
    text(value, valX, y, 9, bold);
    y -= 16;
  };

  if (sharingMode === 'full') {
    for (const section of data.sections) {
      checkY(30);
      text(section.trade.toUpperCase(), MARGIN, y, 7.5, true, gray);
      y -= 14;

      const del = delegations[section.trade];

      for (const item of section.items) {
        checkY(16);
        const key = `${section.trade}::${item.description}`;
        const unitPrice = del?.prices[key] ?? bid.prices[key] ?? 0;
        const lineTotal = item.quantity * unitPrice;
        directCost += lineTotal;

        const desc = item.description.length > 42 ? item.description.slice(0, 40) + '…' : item.description;
        text(desc, COL.desc + 6, y, 8.5);
        text(item.quantity.toLocaleString(), COL.qty, y, 8.5, false, gray);
        text(item.unit, COL.unit, y, 8.5, false, gray);
        text(unitPrice > 0 ? fmtMoney(unitPrice) : '—', COL.price, y, 8.5, false, gray);
        text(lineTotal > 0 ? fmtMoney(lineTotal) : '—', COL.total, y, 8.5);
        y -= 15;
      }
      y -= 4;
    }

    // ── Cost summary (full mode) ──
    checkY(110);
    y -= 8;
    rule(y, W - MARGIN - 200, W - MARGIN, 1, navy);
    y -= 16;

    const oh = directCost * (bid.overheadPct || 0) / 100;
    const profit = directCost * (bid.profitPct || 0) / 100;
    const contingency = directCost * (bid.contingencyPct || 0) / 100;
    const totalBid = directCost + oh + profit + contingency;

    rowLabel('Direct cost', fmtMoney(directCost));
    rowLabel(`Overhead (${bid.overheadPct}%)`, fmtMoney(oh));
    rowLabel(`Profit (${bid.profitPct}%)`, fmtMoney(profit));
    rowLabel(`Contingency (${bid.contingencyPct}%)`, fmtMoney(contingency));
    y -= 2;
    rule(y, W - MARGIN - 200, W - MARGIN);
    y -= 14;
    rowLabel('Total bid', fmtMoney(totalBid), true);
  } else {
    // summary mode: bake overhead/profit/contingency into each trade's displayed price
    const markupFactor = 1
      + (bid.overheadPct || 0) / 100
      + (bid.profitPct || 0) / 100
      + (bid.contingencyPct || 0) / 100;
    let totalBid = 0;

    for (const section of data.sections) {
      checkY(18);
      const del = delegations[section.trade];
      const sectionDirect = section.items.reduce((sum, item) => {
        const key = `${section.trade}::${item.description}`;
        const unitPrice = del?.prices[key] ?? bid.prices[key] ?? 0;
        return sum + item.quantity * unitPrice;
      }, 0);
      const sectionLoaded = sectionDirect * markupFactor;
      totalBid += sectionLoaded;

      text(section.trade, COL.desc + 6, y, 9);
      text(sectionLoaded > 0 ? fmtMoney(sectionLoaded) : '—', COL.total, y, 9);
      y -= 16;
    }
    y -= 4;

    checkY(50);
    y -= 8;
    rule(y, W - MARGIN - 200, W - MARGIN, 1, navy);
    y -= 14;
    rowLabel('Total bid', fmtMoney(totalBid), true);
  }

  text('Generated by BidWise', MARGIN, MARGIN, 7, false, light);

  return pdfDoc.save();
}
