// Bid proposal PDF generation, ported from the share-bid-pdf edge function.
// pdf-lib runs unchanged on Node.
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

interface TakeoffItem { description: string; quantity: number; unit: string; }
interface TakeoffSection { trade: string; items: TakeoffItem[]; }
interface DelegationData { subId: string; prices: Record<string, number>; approvedAt?: string; }
interface CustomLineItem { trade: string; description: string; unit: string; quantity: number; }
interface BidData {
  prices: Record<string, number>;
  delegations?: Record<string, DelegationData>;
  excludedTrades?: string[];
  excludedItems?: string[];
  customItems?: CustomLineItem[];
  overheadPct: number;
  profitPct: number;
  contingencyPct: number;
  finalizedAt?: string;
  sentAt?: string;
}
export interface BidTakeoffData { projectName: string; sections: TakeoffSection[]; bid?: BidData; }

function fmtMoney(n: number): string {
  return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

/** Coerce a stored price (legacy scalar or {material, labor}) into a parts pair. */
function priceParts(v: number | { material?: number; labor?: number } | undefined | null): { material: number; labor: number } {
  if (v == null) return { material: 0, labor: 0 };
  if (typeof v === 'number') return { material: v, labor: 0 };
  return { material: v.material ?? 0, labor: v.labor ?? 0 };
}

export async function generateBidPdf(
  data: BidTakeoffData,
  sharingMode: 'full' | 'summary',
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const W = 612, H = 792, MARGIN = 50;
  let page = pdfDoc.addPage([W, H]);
  let y = H - MARGIN;

  const gray = rgb(0.55, 0.55, 0.55);
  const dark = rgb(0.1, 0.1, 0.1);
  const light = rgb(0.78, 0.78, 0.78);
  const navy = rgb(0.12, 0.20, 0.46);
  const blue = rgb(0.145, 0.388, 0.922); // #2563eb

  const text = (str: string, x: number, yy: number, size: number, bold = false, color = dark) => {
    page.drawText(str, { x, y: yy, size, font: bold ? boldFont : font, color });
  };

  const rule = (yy: number, x1 = MARGIN, x2 = W - MARGIN, thickness = 0.5, color = light) => {
    page.drawLine({ start: { x: x1, y: yy }, end: { x: x2, y: yy }, thickness, color });
  };

  const checkY = (needed: number) => {
    if (y - needed < MARGIN + 30) {
      text('Generated by BidWise', MARGIN, MARGIN, 7, false, light);
      page = pdfDoc.addPage([W, H]);
      y = H - MARGIN;
    }
  };

  // ── Logo (centered) ──
  const logoSize = 32;
  const bidW = boldFont.widthOfTextAtSize('Bid', 20);
  const logoTextW = boldFont.widthOfTextAtSize('BidWise', 20);
  const logoBlockW = logoSize + 10 + logoTextW;
  const logoX = (W - logoBlockW) / 2;
  const iconBottom = y - logoSize;
  page.drawRectangle({ x: logoX, y: iconBottom, width: logoSize, height: logoSize, color: blue });
  page.drawLine({ start: { x: logoX + 8.67, y: iconBottom + 15 }, end: { x: logoX + 13.67, y: iconBottom + 10 }, thickness: 3, color: rgb(1, 1, 1) });
  page.drawLine({ start: { x: logoX + 13.67, y: iconBottom + 10 }, end: { x: logoX + 23.33, y: iconBottom + 20.67 }, thickness: 3, color: rgb(1, 1, 1) });
  const wordX = logoX + logoSize + 10;
  const wordY = iconBottom + (logoSize - 20) / 2;
  text('Bid', wordX, wordY, 20, true, dark);
  text('Wise', wordX + bidW, wordY, 20, true, blue);
  y -= logoSize + 20;

  // ── Header ──
  text('Bid Proposal', MARGIN, y, 22, true, navy);
  y -= 28;
  text(data.projectName, MARGIN, y, 14, true);
  y -= 18;
  const finalDate = data.bid?.finalizedAt
    ? new Date(data.bid.finalizedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : '';
  text(`Finalized: ${finalDate}`, MARGIN, y, 9, false, gray);
  y -= 24;
  rule(y, MARGIN, W - MARGIN, 1, navy);
  y -= 20;

  // ── Column headers ──
  const COL = { desc: MARGIN, qty: 248, unit: 286, material: 326, labor: 396, total: W - MARGIN - 55 };
  if (sharingMode === 'full') {
    text('DESCRIPTION', COL.desc, y, 7, true, gray);
    text('QTY', COL.qty, y, 7, true, gray);
    text('UNIT', COL.unit, y, 7, true, gray);
    text('MATERIAL', COL.material, y, 7, true, gray);
    text('LABOR', COL.labor, y, 7, true, gray);
    text('TOTAL', COL.total, y, 7, true, gray);
  } else {
    text('TRADE', COL.desc, y, 7, true, gray);
    text('SUBTOTAL', COL.total, y, 7, true, gray);
  }
  y -= 12;
  rule(y);
  y -= 10;

  const bid = data.bid!;
  const delegations = bid.delegations ?? {};
  const excludedTrades = new Set(bid.excludedTrades ?? []);
  const excludedItems = new Set(bid.excludedItems ?? []);

  // Merge user-added custom items into the AI sections (appending to a matching trade or
  // creating a new one) so they appear in the proposal alongside the generated items.
  const merged: TakeoffSection[] = data.sections.map((s) => ({ ...s, items: [...s.items] }));
  const byTrade = new Map(merged.map((s) => [s.trade, s]));
  for (const ci of bid.customItems ?? []) {
    const item: TakeoffItem = { description: ci.description, quantity: ci.quantity, unit: ci.unit };
    const existing = byTrade.get(ci.trade);
    if (existing) existing.items.push(item);
    else {
      const ns: TakeoffSection = { trade: ci.trade, items: [item] };
      merged.push(ns);
      byTrade.set(ci.trade, ns);
    }
  }

  // Excluded trades and struck-out line items are dropped from the proposal entirely;
  // a section left with no items after filtering is omitted too.
  const sections = merged
    .filter((s) => !excludedTrades.has(s.trade))
    .map((s) => ({
      ...s,
      items: s.items.filter((it) => !excludedItems.has(`${s.trade}::${it.description}`)),
    }))
    .filter((s) => s.items.length > 0);
  let directCost = 0;
  let materialDirect = 0;
  let laborDirect = 0;

  const rowLabel = (label: string, value: string, bold = false) => {
    text(label, W - MARGIN - 195, y, 9, bold);
    const valX = W - MARGIN - font.widthOfTextAtSize(value, 9);
    text(value, valX, y, 9, bold);
    y -= 16;
  };

  if (sharingMode === 'full') {
    for (const section of sections) {
      checkY(30);
      text(section.trade.toUpperCase(), MARGIN, y, 7.5, true, gray);
      y -= 14;

      const del = delegations[section.trade];

      for (const item of section.items) {
        checkY(16);
        const key = `${section.trade}::${item.description}`;
        const parts = priceParts(del?.prices[key] ?? bid.prices[key]);
        const lineMaterial = item.quantity * parts.material;
        const lineLabor = item.quantity * parts.labor;
        const lineTotal = lineMaterial + lineLabor;
        directCost += lineTotal;
        materialDirect += lineMaterial;
        laborDirect += lineLabor;

        const desc = item.description.length > 34 ? item.description.slice(0, 32) + '…' : item.description;
        text(desc, COL.desc + 6, y, 8.5);
        text(item.quantity.toLocaleString(), COL.qty, y, 8.5, false, gray);
        text(item.unit, COL.unit, y, 8.5, false, gray);
        text(lineMaterial > 0 ? fmtMoney(lineMaterial) : '—', COL.material, y, 8.5, false, gray);
        text(lineLabor > 0 ? fmtMoney(lineLabor) : '—', COL.labor, y, 8.5, false, gray);
        text(lineTotal > 0 ? fmtMoney(lineTotal) : '—', COL.total, y, 8.5);
        y -= 15;
      }
      y -= 4;
    }

    // ── Cost summary (full mode) ──
    checkY(140);
    y -= 8;
    rule(y, W - MARGIN - 200, W - MARGIN, 1, navy);
    y -= 16;

    const oh = directCost * (bid.overheadPct || 0) / 100;
    const profit = directCost * (bid.profitPct || 0) / 100;
    const contingency = directCost * (bid.contingencyPct || 0) / 100;
    const totalBid = directCost + oh + profit + contingency;

    rowLabel('Materials', fmtMoney(materialDirect));
    rowLabel('Labor', fmtMoney(laborDirect));
    rowLabel('Direct cost', fmtMoney(directCost));
    rowLabel(`Overhead (${bid.overheadPct}%)`, fmtMoney(oh));
    rowLabel(`Profit (${bid.profitPct}%)`, fmtMoney(profit));
    rowLabel(`Contingency (${bid.contingencyPct}%)`, fmtMoney(contingency));
    y -= 2;
    rule(y, W - MARGIN - 200, W - MARGIN);
    y -= 14;
    rowLabel('Total bid', fmtMoney(totalBid), true);
  } else {
    // summary mode: bake overhead/profit/contingency into each trade's displayed price
    const markupFactor = 1
      + (bid.overheadPct || 0) / 100
      + (bid.profitPct || 0) / 100
      + (bid.contingencyPct || 0) / 100;
    let totalBid = 0;
    let materialDirect = 0;
    let laborDirect = 0;

    for (const section of sections) {
      checkY(18);
      const del = delegations[section.trade];
      let sectionDirect = 0;
      for (const item of section.items) {
        const key = `${section.trade}::${item.description}`;
        const parts = priceParts(del?.prices[key] ?? bid.prices[key]);
        materialDirect += item.quantity * parts.material;
        laborDirect += item.quantity * parts.labor;
        sectionDirect += item.quantity * (parts.material + parts.labor);
      }
      const sectionLoaded = sectionDirect * markupFactor;
      totalBid += sectionLoaded;

      text(section.trade, COL.desc + 6, y, 9);
      text(sectionLoaded > 0 ? fmtMoney(sectionLoaded) : '—', COL.total, y, 9);
      y -= 16;
    }
    y -= 4;

    checkY(70);
    y -= 8;
    rule(y, W - MARGIN - 200, W - MARGIN, 1, navy);
    y -= 16;
    // Materials/labor shown as the loaded (marked-up) split so the parts sum to the total bid.
    rowLabel('Materials', fmtMoney(materialDirect * markupFactor));
    rowLabel('Labor', fmtMoney(laborDirect * markupFactor));
    y -= 2;
    rule(y, W - MARGIN - 200, W - MARGIN);
    y -= 14;
    rowLabel('Total bid', fmtMoney(totalBid), true);
  }

  text('Generated by BidWise', MARGIN, MARGIN, 7, false, light);

  return pdfDoc.save();
}
